# See https://github.com/silverstripe/silverstripe-travis-support for setup details

sudo: false

language: php

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=4.0
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=4.0
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=4

before_script:
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require "silverstripe/cms"
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit --coverage-clover coverage.clover dashboard/tests

after_success:
  - mv coverage.clover ~/build/$TRAVIS_REPO_SLUG/
  - cd ~/build/$TRAVIS_REPO_SLUG
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
