language: php

env:
  global:
    - COMPOSER_ROOT_VERSION=5.0.x-dev

matrix:
  include:
    - php: 5.3
      dist: precise
      env: DB=MYSQL SILVERSTRIPE_VERSION=3.2 PHPUNIT_TEST=1
    - php: 5.5
      env: DB=MYSQL SILVERSTRIPE_VERSION=3.4 PHPUNIT_TEST=1
    - php: 5.5
      env: DB=MYSQL SILVERSTRIPE_VERSION=3.4 PHPUNIT_TEST=1
    - php: 5.6
      env: DB=MYSQL SILVERSTRIPE_VERSION=3.5 PHPCS_TEST=1 PHPUNIT_TEST=1
    - php: 7.0
      env: DB=MYSQL SILVERSTRIPE_VERSION=3.6 PHPUNIT_COVERAGE_TEST=1
    - php: 7.1
      env: DB=MYSQL SILVERSTRIPE_VERSION=3.7 PHPUNIT_TEST=1
    - php: 7.2
      env: DB=MYSQL SILVERSTRIPE_VERSION=3 PHPUNIT_TEST=1

services:
  - mysql
  - postgresql

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit=2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  - composer validate
  - composer require --no-update silverstripe/cms:$SILVERSTRIPE_VERSION
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:1.2.1; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml -vvv; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
