version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard.yml

jobs:
  include:
    - php: 8.1
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="5.0.x-dev"
        - PHPUNIT_TEST=1
        - PHPUNIT_COVERAGE_TEST=1
    - php: 8.`
      env:
        - DB=PGSQL
        - REQUIRE_INSTALLER="5.x-dev"
        - PHPUNIT_TEST=1
        - PHPCS_TEST=1
