version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard.yml

jobs:
  include:
    - php: 7.2
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="4.5.x-dev"
        - PHPUNIT_TEST=1
    - php: 7.3
      env:
        - DB=PGSQL
        - REQUIRE_INSTALLER="4.7.x-dev"
        - PHPUNIT_TEST=1
        - PHPCS_TEST=1
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="4.9.x-dev"
        - PHPUNIT_TEST=1
        - PHPUNIT_COVERAGE_TEST=1
    - php: 8.0
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="4.10.x-dev"
        - PHPUNIT_TEST=1
    - php: 8.1
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="4.x-dev"
        - PHPUNIT_TEST=1T_TEST=1
