version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard.yml

jobs:
  include:
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="4.x-dev"
        - NPM_TEST=1
    - php: 7.4
      env:
        - DB=PGSQL
        - REQUIRE_INSTALLER="4.x-dev"
        - PHPUNIT_TEST=1
        - PHPCS_TEST=1
