---
Name: dashboardconfig
After:
    - '#cmsdefaultadmin'
---
SilverStripe\Admin\AdminRootController:
  default_panel: Plastyk\Dashboard\Admin\DashboardAdmin

Plastyk\Dashboard\Admin\DashboardAdmin:
  extensions:
    - Plastyk\Dashboard\Extensions\DashboardSearchExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Plastyk\Dashboard\Extensions\DashboardSiteTreeExtension

SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.plastykDashboardCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "plastykDashboardCache"
      defaultLifetime: 3600

Plastyk\Dashboard\Panels\UsefulLinksPanel:
  links:
    - Link: https://analytics.google.com/analytics/web/
      Title: Google Analytics
      Description: Website traffic reports to see how many people are visiting your website.
    - Link: https://whatsmybrowser.org/
      Title: What's my browser
      Description: Information on what browser you are currently using.
